### ISSUE TITLE
Requests is deprecated in the new WP Version 6.2

### ISSUE THREAD

**Issue by migueliriano** [lipemat/wp-unit#2]
`Requests` class going to be deprecated in the new WP Version 6.2, to avoid errors we have to use `WpOrg\Requests\Requests` instead.

![image](https://user-images.githubusercontent.com/5392202/224142750-bc93ad06-52d3-4ed0-a09d-70360f18cf1f.png)

I created this PR to fix it https://github.com/lipemat/wp-unit/pull/1

**Comment by lipemat** [comment]
Fixed in https://github.com/lipemat/wp-unit/releases/tag/3.2.0
